################################################################################################
#Module 00. Load raw xml, parsing, save as rds
################################################################################################
rm(list=ls())
setwd("G:/내 드라이브/Rrunning/HW055/")
library(xml2)
files <- list.files("AJD", pattern="\\.xml$", full.names=TRUE); dl <- list()
for(i in seq_along(files)) { txt <- paste(readLines(files[i], warn=F, encoding="UTF-8"), collapse=" "); it <- xml_find_all(read_xml(gsub("&#[xX]?[0-9a-fA-F]+;", "", txt)), "//*[front/biblioData[@type='T']]"); if(length(it)>0) dl[[i]] <- data.frame(id=xml_attr(it, "id"), t=xml_text(xml_find_first(it, ".//text/content")), stringsAsFactors=F) }
df <- do.call(rbind, dl); saveRDS(df, "Output_20260929/00_sillok_raw_data_hanja.rds")

################################################################################################
#Module 01. Load rds file, and feature assessment
################################################################################################
rm(list=ls())
setwd("G:/내 드라이브/Rrunning/HW055/")
library(ggplot2); library(stringr); library(maps)

# Load rds file
df <- readRDS("Output_20260929/00_sillok_raw_data_hanja.rds")

# Regional feature assignment
df$Seoul=str_count(df$t,"京城|漢城|漢陽"); df$GG=str_count(df$t,"京畿"); df$CC=str_count(df$t,"忠淸|湖西"); df$JL=str_count(df$t,"全羅|湖南"); df$GS=str_count(df$t,"慶尙|嶺南"); df$GW=str_count(df$t,"江原|關東"); df$HH=str_count(df$t,"黃海|海西"); df$PA=str_count(df$t,"平安|關西"); df$HG=str_count(df$t,"咸吉|咸鏡|關北"); df$JJ=str_count(df$t,"濟州|耽羅")

################################################################################################
#Module 02. Assignment of feature: politics, economy, society, culture, diplomacy, natural disasters, and diseases
################################################################################################
df$Pol=str_count(df$t,"叛亂|逆謀|鞫問|罷職|上疏"); df$Eco=str_count(df$t,"饑饉|凶年|賑恤|還上|貢物"); df$Soc=str_count(df$t,"盜賊|殺人|訴訟|流民|火賊"); df$Cul=str_count(df$t,"祭祀|科擧|書院|僧侶|成均館"); df$Dip=str_count(df$t,"使臣|倭寇|野人|朝貢|胡虜"); df$Nat=str_count(df$t,"地震|日食|彗星|水災|旱災"); df$Dis=str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂")
freq <- t(as.matrix(df[, c("Seoul","GG","CC","JL","GS","GW","HH","PA","HG","JJ")]) > 0) %*% as.matrix(df[, c("Pol","Eco","Soc","Cul","Dip","Nat","Dis")])
df_p <- merge(as.data.frame(as.table(freq)), data.frame(Var1=c("Seoul","GG","CC","JL","GS","GW","HH","PA","HG","JJ"), lon=c(126.8, 127.5, 126.8, 127.1, 128.5, 128.3, 125.7, 125.7, 127.5, 126.5), lat=c(37.6, 37.1, 36.5, 35.5, 35.8, 37.8, 38.3, 39.5, 40.5, 33.3)))
df_dis <- df_p[df_p$Var2 == "Dis", ]; df_bar <- df_p[df_p$Var2 != "Dis", ]; df_bar$xmin <- df_bar$lon + as.numeric(factor(df_bar$Var2))*0.1 - 0.35; df_bar$xmax <- df_bar$xmin + 0.08; df_bar$ymin <- df_bar$lat; df_bar$ymax <- df_bar$lat + (df_bar$Freq / max(df_bar$Freq)) * 1.0
write.table(df_p, "Output_20260929/02_sillok_map_stats_v2.txt", sep="\t", row.names=F, fileEncoding="UTF-8")
pdf("Output_20260929/02_sillok_map_analysis_v2.pdf", width=9, height=12)
print(ggplot() + geom_polygon(data=map_data("world", region=c("South Korea", "North Korea")), aes(x=long, y=lat, group=group), fill="gray95", color="white") + geom_point(data=df_dis, aes(x=lon, y=lat, color=Freq), size=20, alpha=0.6) + scale_color_gradient(low="lightblue", high="darkred", name="Disease Intensity") + geom_rect(data=df_bar, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=Var2)) + scale_fill_brewer(palette="Set2", name="Categories") + geom_text(data=unique(df_p[, c("Var1","lon","lat")]), aes(x=lon, y=lat-0.2, label=Var1), size=4, fontface="bold") + labs(title="Joseon Dynasty Regional Crisis Mapping") + coord_fixed(1.3) + theme_void()); dev.off(); Sys.time()

################################################################################################
#Module 03. Spatio-temporal Hovmoller diagram and crisis propagation metrics
################################################################################################
df$vol=substr(df$id,1,7); df$Pol=str_count(df$t,"叛亂|逆謀|鞫問|罷職|上疏"); df$Eco=str_count(df$t,"饑饉|凶年|賑恤|還上|貢物"); df$Soc=str_count(df$t,"盜賊|殺人|訴訟|流民|火賊"); df$Cul=str_count(df$t,"祭祀|科擧|書院|僧侶|成均館"); df$Dip=str_count(df$t,"使臣|倭寇|野人|朝貢|胡虜"); df$Nat=str_count(df$t,"地震|日食|彗星|水災|旱災"); df$Dis=str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂")
regs <- c("JJ","JL","GS","CC","GG","Seoul","GW","HH","PA","HG"); vars <- c("Dis","Nat","Eco","Soc","Pol","Cul","Dip"); h_list <- list(); s_list <- list(); idx <- 1
for(r in regs) { m <- rowsum(as.matrix(df[,vars])*(df[,r]>0), df$vol); td <- as.data.frame(as.table(m)); td$Region <- r; h_list[[r]] <- td; for(v in vars) { x <- m[,v]; s_list[[idx]] <- data.frame(Region=r, Variable=v, Total_Freq=sum(x), Mean_Freq=round(mean(x),2), Max_Spike=max(x), Peak_Vol=rownames(m)[which.max(x)], Active_Vols=sum(x>0), Persistence_Pct=round(mean(x>0)*100,2), Temporal_CoM=round(sum(seq_along(x)*x)/max(1,sum(x)),1), Burstiness=round((sd(x)-mean(x))/(sd(x)+mean(x)+1e-9),3), stringsAsFactors=FALSE); idx <- idx+1 } }
hov_df <- do.call(rbind, h_list); stat_df <- do.call(rbind, s_list); hov_df$Region <- factor(hov_df$Region, levels=regs); hov_df$Var2 <- factor(hov_df$Var2, levels=vars); hov_df$LogFreq <- log1p(hov_df$Freq)
write.table(stat_df, "Output_20260929/03_hovmoller_stats.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8"); write.table(hov_df, "Output_20260929/03_hovmoller_matrix.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8")
pdf("Output_20260929/03_hovmoller_diagram.pdf", width=14, height=12); print(ggplot(hov_df, aes(x=Var1, y=Region, fill=LogFreq)) + geom_tile() + facet_wrap(~Var2, ncol=1) + scale_fill_gradientn(colours=c("white","#fee090","#f46d43","#a50026"), name="log(Freq+1)") + labs(title="Spatio-Temporal Hovmoller Diagram Across Joseon Dynasty", subtitle="Latitude-ordered Regional Propagation (South to North) across Chronological Volumes", x="Chronological Volume ID", y="Region (South to North)") + theme_minimal() + theme(axis.text.x=element_text(angle=90, hjust=1, size=4), strip.text=element_text(face="bold", size=10), panel.grid=element_blank())); dev.off()



################################################################################################
#Module 03-2. Spatio-temporal disease contour mapping using lattice (X-axis: Year)
################################################################################################
library(lattice); library(stringr); df$vol <- substr(df$id,1,7); df$Dis <- str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂"); regs <- c("JJ","JL","GS","CC","GG","Seoul","GW","HH","PA","HG"); d_mat <- rowsum((as.matrix(df[,regs])>0)*df$Dis, df$vol)
s_mat <- as.matrix(stats::filter(log1p(d_mat), rep(1/11, 11), sides=2)); s_mat[is.na(s_mat)] <- 0; W <- diag(0.6, 10); W[abs(row(W)-col(W))==1] <- 0.2; z_mat <- s_mat %*% W; colnames(z_mat) <- regs; rownames(z_mat) <- rownames(d_mat)
yr_v <- c(1392,1399,1401,1418,1450,1452,1455,1468,1469,1494,1506,1544,1545,1567,1608,1623,1649,1659,1674,1720,1724,1776,1800,1834,1849,1863)[match(substr(rownames(z_mat),2,2),letters)] + ifelse(substr(rownames(z_mat),2,3)=="zb",44,0) + pmax(0,as.numeric(substr(rownames(z_mat),6,7))-1); yr_v[is.na(yr_v)] <- round(seq(1392,1894,length.out=nrow(z_mat)))[is.na(yr_v)]
c_list <- list(); q75 <- quantile(z_mat[z_mat>0], 0.75); for(i in seq_along(regs)) { y <- z_mat[,i]; r_raw <- d_mat[,i]; c_list[[i]] <- data.frame(Region=regs[i], Raw_Total=sum(r_raw), Contour_Mean=round(mean(y),3), Contour_Max=round(max(y),3), Peak_Wave_Vol=rownames(z_mat)[which.max(y)], Peak_Year=yr_v[which.max(y)], High_Contour_Vols=sum(y>=q75), Wave_Ratio_Pct=round(mean(y>=q75)*100,2), stringsAsFactors=FALSE) }
c_stats <- do.call(rbind, c_list); write.table(c_stats, "Output_20260929/03_dis_contour_stats.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8"); idx_x <- seq(1, nrow(z_mat), by=15); pdf("Output_20260929/03_dis_contour.pdf", width=14, height=7); print(levelplot(z_mat, aspect="fill", contour=TRUE, region=TRUE, cuts=12, col.regions=colorRampPalette(c("white","#ffffbf","#fdae61","#d7191c","#67001f"))(100), main="Spatio-Temporal Disease (Dis) Epidemic Contour Map (Joseon Dynasty)", xlab="Year (Chronological Progression)", ylab="Region (South to North)", scales=list(x=list(at=idx_x, labels=yr_v[idx_x], rot=90, cex=0.55), y=list(cex=0.9)))); dev.off()

################################################################################################
#Module 03-3. Spatio-temporal disease Lexis surface and cohort dynamics (X-axis: Year)
################################################################################################
library(ggplot2); df$vol <- substr(df$id,1,7); df$king <- substr(df$id,1,3); df$Dis <- str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂"); regs <- c("JJ","JL","GS","CC","GG","Seoul","GW","HH","PA","HG"); d_mat <- rowsum((as.matrix(df[,regs])>0)*df$Dis, df$vol)
s_mat <- as.matrix(stats::filter(log1p(d_mat), rep(1/11,11), sides=2)); s_mat[is.na(s_mat)] <- 0; W <- diag(0.6,10); W[abs(row(W)-col(W))==1] <- 0.2; z_mat <- s_mat%*%W; colnames(z_mat) <- regs; rownames(z_mat) <- rownames(d_mat); k_brk <- which(!duplicated(substr(rownames(z_mat),1,3)))
yr_v <- c(1392,1399,1401,1418,1450,1452,1455,1468,1469,1494,1506,1544,1545,1567,1608,1623,1649,1659,1674,1720,1724,1776,1800,1834,1849,1863)[match(substr(rownames(z_mat),2,2),letters)] + ifelse(substr(rownames(z_mat),2,3)=="zb",44,0) + pmax(0,as.numeric(substr(rownames(z_mat),6,7))-1); yr_v[is.na(yr_v)] <- round(seq(1392,1894,length.out=nrow(z_mat)))[is.na(yr_v)]; lx_df <- as.data.frame(as.table(z_mat)); lx_df$t_idx <- as.numeric(lx_df$Var1); lx_df$r_idx <- as.numeric(lx_df$Var2); colnames(lx_df) <- c("Vol","Region","Intensity","t_idx","r_idx"); k_vec <- substr(rownames(z_mat),1,3); r_age <- ave(seq_len(nrow(z_mat)), k_vec, FUN=seq_along)/ave(seq_len(nrow(z_mat)), k_vec, FUN=length)
lx_list <- list(); for(i in seq_along(regs)) { z <- z_mat[,i]; dt <- c(0,diff(z)); dy <- if(i==1) z_mat[,2]-z else if(i==10) z-z_mat[,9] else (z_mat[,i+1]-z_mat[,i-1])/2; d_lag <- if(i>1) cor(z[-1], z_mat[-nrow(z_mat),i-1]) else NA; lx_list[[i]] <- data.frame(Region=regs[i], Surface_Integral=round(sum(z),2), Surface_Max=round(max(z),3), Max_Temporal_Surge=round(max(dt),3), Mean_Spatial_Grad=round(mean(abs(dy)),3), Diag_Wave_Corr=round(d_lag,3), Early_Reign_Mean=round(mean(z[r_age<=0.3]),3), Late_Reign_Mean=round(mean(z[r_age>=0.7]),3), Late_to_Early_Ratio=round(mean(z[r_age>=0.7])/(mean(z[r_age<=0.3])+1e-9),2), Peak_Lexis_Coord=paste0(yr_v[which.max(z)],"(",rownames(z_mat)[which.max(z)],")@",regs[i]), stringsAsFactors=FALSE) }
lx_stats <- do.call(rbind, lx_list); pk_df <- lx_df[order(-lx_df$Intensity)[1:10],]; write.table(lx_stats, "Output_20260929/03_dis_lexis_stats.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8"); idx_x <- seq(1, nrow(z_mat), by=15); pdf("Output_20260929/03_dis_lexis_surface.pdf", width=14, height=7); print(ggplot(lx_df, aes(x=t_idx, y=r_idx)) + geom_raster(aes(fill=Intensity), interpolate=TRUE) + geom_contour(aes(z=Intensity), color="black", alpha=0.45, linewidth=0.35, bins=12) + geom_vline(xintercept=k_brk, color="gray30", linetype="dotted", linewidth=0.3) + geom_abline(intercept=seq(-60, 0, by=5), slope=0.1, color="white", linetype="dashed", alpha=0.35, linewidth=0.3) + geom_point(data=pk_df, aes(x=t_idx, y=r_idx), color="cyan", size=2, shape=8) + scale_fill_gradientn(colours=c("#053061","#2166ac","#f7f7f7","#ef8a62","#b2182b","#67001f"), name="Lexis\nIntensity") + scale_x_continuous(breaks=idx_x, labels=yr_v[idx_x], expand=c(0,0)) + scale_y_continuous(breaks=1:10, labels=regs, expand=c(0,0)) + labs(title="Spatio-Temporal Lexis Surface of Epidemic Outbreaks (Dis) Across Joseon Dynasty", subtitle="Interpolated Epidemic Surface with Iso-Contour Ridges, Reign Cohort Boundaries (Dotted), and Propagation Diagonals (Dashed)", x="Chronological Year (Reign Cohorts)", y="Spatial Stratum (South to North)") + theme_minimal() + theme(axis.text.x=element_text(angle=90, hjust=1, size=5), axis.text.y=element_text(face="bold", size=9), panel.grid=element_blank())); dev.off()


################################################################################################
#Module 04. Regional Granger causality analysis and Directed Acyclic Graph (DAG) visualization
################################################################################################
library(ggplot2); library(stringr); library(grid); df$vol <- substr(df$id,1,7); df$Pol <- str_count(df$t,"叛亂|逆謀|鞫問|罷職|上疏"); df$Eco <- str_count(df$t,"饑饉|凶年|賑恤|還上|貢物"); df$Soc <- str_count(df$t,"盜賊|殺人|訴訟|流民|火賊"); df$Cul <- str_count(df$t,"祭祀|科擧|書院|僧侶|成均館"); df$Dip <- str_count(df$t,"使臣|倭寇|野人|朝貢|胡虜"); df$Nat <- str_count(df$t,"地震|日食|彗星|水災|旱災"); df$Dis <- str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂")
regs <- c("JJ","JL","GS","CC","GG","Seoul","GW","HH","PA","HG"); vars <- c("Dis","Nat","Eco","Soc","Pol","Cul","Dip"); ang <- seq(pi/2, 2*pi+pi/2, length.out=8)[1:7]; vx <- cos(ang); vy <- sin(ang); e_list <- list(); n_list <- list(); idx <- 1
for(r in regs) { m <- log1p(rowsum(as.matrix(df[,vars])*(df[,r]>0), df$vol)); n <- nrow(m); f_mat <- matrix(0,7,7,dimnames=list(vars,vars)); p_mat <- matrix(1,7,7,dimnames=list(vars,vars)); for(i in 1:7) { for(j in 1:7) { if(i!=j && n>12) { y <- m[4:n,j]; x0 <- cbind(1,m[3:(n-1),j],m[2:(n-2),j],m[1:(n-3),j]); x1 <- cbind(x0,m[3:(n-1),i],m[2:(n-2),i],m[1:(n-3),i]); r0 <- sum(lm.fit(x0,y)$residuals^2); r1 <- sum(lm.fit(x1,y)$residuals^2); fv <- max(0,((r0-r1)/3)/(r1/(n-10)+1e-9)); f_mat[i,j] <- fv; p_mat[i,j] <- pf(fv,3,n-10,lower.tail=FALSE) } } }; net_f <- rowSums(f_mat)-colSums(f_mat); rk <- rank(-net_f, ties.method="first"); n_list[[r]] <- data.frame(Region=r, Var=vars, x=vx, y=vy, Net_Flow=round(net_f,2), Topo_Rank=rk, stringsAsFactors=FALSE); thr <- quantile(f_mat[f_mat>0], 0.55); for(i in 1:7) { for(j in 1:7) { if(rk[i]<rk[j] && (p_mat[i,j]<0.05 || f_mat[i,j]>=thr)) { dx <- vx[j]-vx[i]; dy <- vy[j]-vy[i]; d_len <- sqrt(dx^2+dy^2); e_list[[idx]] <- data.frame(Region=r, From=vars[i], To=vars[j], F_Stat=round(f_mat[i,j],3), P_Val=round(p_mat[i,j],5), Role=ifelse(vars[j]=="Dis","1_Pre-Dis (Cause -> Dis)",ifelse(vars[i]=="Dis","2_Post-Dis (Dis -> Effect)","3_Inter-Crisis (Other DAG)")), x1=vx[i]+0.22*dx/d_len, y1=vy[i]+0.22*dy/d_len, x2=vx[j]-0.26*dx/d_len, y2=vy[j]-0.26*dy/d_len, stringsAsFactors=FALSE); idx <- idx+1 } } } }
dag_edges <- do.call(rbind, e_list); dag_nodes <- do.call(rbind, n_list); dag_edges$Region <- factor(dag_edges$Region, levels=regs); dag_nodes$Region <- factor(dag_nodes$Region, levels=regs); write.table(dag_edges[,c("Region","From","To","Role","F_Stat","P_Val")], "Output_20260929/04_granger_dag_stats.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8")
pdf("Output_20260929/04_granger_dag.pdf", width=16, height=7.5); print(ggplot() + geom_segment(data=dag_edges, aes(x=x1, y=y1, xend=x2, yend=y2, linewidth=F_Stat, color=Role, alpha=Role), arrow=arrow(length=unit(0.18,"cm"), type="closed")) + geom_point(data=dag_nodes, aes(x=x, y=y, fill=Net_Flow), shape=21, size=9, color="gray20", stroke=0.8) + geom_text(data=dag_nodes, aes(x=x, y=y, label=Var), size=2.8, fontface="bold", color="black") + facet_wrap(~Region, ncol=5) + scale_linewidth_continuous(range=c(0.3, 2.6), name="Granger F-Stat\n(Arrow Width)") + scale_color_manual(values=c("1_Pre-Dis (Cause -> Dis)"="#d7191c", "2_Post-Dis (Dis -> Effect)"="#2b83ba", "3_Inter-Crisis (Other DAG)"="gray60"), name="Causal Direction") + scale_alpha_manual(values=c("1_Pre-Dis (Cause -> Dis)"=0.95, "2_Post-Dis (Dis -> Effect)"=0.95, "3_Inter-Crisis (Other DAG)"=0.45), guide="none") + scale_fill_gradient2(low="#4575b4", mid="white", high="#fdae61", midpoint=0, name="Net Causal\nOutflow") + coord_fixed(xlim=c(-1.35,1.35), ylim=c(-1.35,1.35)) + labs(title="Regional Granger Causality Directed Acyclic Graphs (DAG) Centered on Epidemic Outbreaks (Dis)", subtitle="Red: Antecedent Causes of Dis (X -> Dis) | Blue: Subsequent Effects of Dis (Dis -> Y) | Edge Width: Granger Causality F-Statistic", x=NULL, y=NULL) + theme_minimal() + theme(axis.text=element_blank(), panel.grid=element_blank(), strip.text=element_text(face="bold", size=11), legend.position="right")); dev.off()

################################################################################################
#Module 05. Panel VAR & Orthogonalized IRF: Crisis Peak, Resilience Half-Life, and Catastrophe
################################################################################################
library(ggplot2); library(stringr); df$vol <- substr(df$id,1,7); df$Pol <- str_count(df$t,"叛亂|逆謀|鞫問|罷職|上疏"); df$Eco <- str_count(df$t,"饑饉|凶年|賑恤|還上|貢物"); df$Soc <- str_count(df$t,"盜賊|殺人|訴訟|流民|火賊"); df$Nat <- str_count(df$t,"地震|日食|彗星|水災|旱災"); df$Dis <- str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂"); regs <- c("JJ","JL","GS","CC","GG","Seoul","GW","HH","PA","HG"); vars <- c("Nat","Eco","Dis","Soc","Pol")
y_all <- NULL; x_all <- NULL; r_mats <- list(); for(r in regs) { m <- scale(log1p(rowsum(as.matrix(df[,vars])*(df[,r]>0), df$vol))); m[is.na(m)] <- 0; n <- nrow(m); r_mats[[r]] <- m; if(n>5) { y_all <- rbind(y_all, m[3:n,]); x_all <- rbind(x_all, cbind(m[2:(n-1),], m[1:(n-2),])) } }
pairs_m <- rbind(c("Dis","Eco","1_Post-Dis: Dis -> Eco (Famine)"), c("Dis","Soc","1_Post-Dis: Dis -> Soc (Unrest)"), c("Dis","Pol","1_Post-Dis: Dis -> Pol (Rebellion)"), c("Dis","Nat","1_Post-Dis: Dis -> Nat (Co-Disaster)"), c("Eco","Dis","2_Pre-Dis: Eco (Famine) -> Dis"), c("Soc","Dis","2_Pre-Dis: Soc (Unrest) -> Dis"), c("Pol","Dis","2_Pre-Dis: Pol (Rebellion) -> Dis"), c("Nat","Dis","2_Pre-Dis: Nat (Disaster) -> Dis"))
irf_l <- list(); st_l <- list(); idx1 <- 1; idx2 <- 1; all_scopes <- c("Panel_FE", regs); for(sc in all_scopes) { if(sc=="Panel_FE") { Y <- y_all; X <- x_all } else { m <- r_mats[[sc]]; n <- nrow(m); Y <- m[3:n,]; X <- cbind(m[2:(n-1),], m[1:(n-2),]) }; fit <- lm.fit(X, Y); B <- fit$coefficients; B[is.na(B)] <- 0; A1 <- t(B[1:5,]); A2 <- t(B[6:10,]); sig <- cov(fit$residuals) + diag(1e-5,5); P <- t(chol(sig)); comp <- rbind(cbind(A1,A2), cbind(diag(5),matrix(0,5,5))); rho <- max(Mod(eigen(comp)$values)); Phi <- array(0,c(5,5,16)); Th <- array(0,c(5,5,16)); Phi[,,1] <- diag(5); Phi[,,2] <- A1; for(h in 3:16) { Phi[,,h] <- A1%*%Phi[,,h-1] + A2%*%Phi[,,h-2] }; for(h in 1:16) { Th[,,h] <- Phi[,,h]%*%P }; for(k in 1:nrow(pairs_m)) { imp <- match(pairs_m[k,1],vars); rsp <- match(pairs_m[k,2],vars); v_irf <- as.numeric(Th[rsp,imp,]); v_cum <- cumsum(v_irf); pk_h <- which.max(abs(v_irf))-1; pk_v <- v_irf[pk_h+1]; post_pk <- which((0:15)>pk_h & abs(v_irf)<=0.5*abs(pk_v)); hl_h <- if(length(post_pk)>0) min(post_pk)-1 else 15; rec_h <- if(any((0:15)>pk_h & abs(v_irf)<=0.1*abs(pk_v))) min(which((0:15)>pk_h & abs(v_irf)<=0.1*abs(pk_v)))-1 else 15; res_idx <- round((1-rho)*100/(hl_h-pk_h+1),3); cat_st <- ifelse(rho>=0.85 | max(abs(v_cum))>=0.6, "Catastrophic_Hysteresis", "Resilient_Damped"); irf_l[[idx1]] <- data.frame(Scope=sc, Pair=pairs_m[k,3], Dir_Group=substr(pairs_m[k,3],1,10), Horizon=0:15, IRF=v_irf, Cum_IRF=v_cum, Peak_H=pk_h, HalfLife_H=hl_h, Regime=cat_st, stringsAsFactors=FALSE); idx1 <- idx1+1; st_l[[idx2]] <- data.frame(Scope=sc, Impulse=pairs_m[k,1], Response=pairs_m[k,2], Pathway=pairs_m[k,3], Spectral_Radius=round(rho,3), Peak_Lag_Vol=pk_h, Peak_Amplitude=round(pk_v,4), HalfLife_Lag_Vol=hl_h, Full_Recovery_Lag=rec_h, Cum_Hysteresis_H15=round(v_cum[16],4), Resilience_Index=res_idx, System_State=cat_st, stringsAsFactors=FALSE); idx2 <- idx2+1 } }
irf_df <- do.call(rbind, irf_l); st_df <- do.call(rbind, st_l); p_df <- irf_df[irf_df$Scope=="Panel_FE",]; r_df <- irf_df[irf_df$Scope!="Panel_FE",]; q_lo <- ave(r_df$IRF, r_df$Pair, r_df$Horizon, FUN=min); q_hi <- ave(r_df$IRF, r_df$Pair, r_df$Horizon, FUN=max); r_band <- unique(data.frame(Pair=r_df$Pair, Horizon=r_df$Horizon, ymin=q_lo, ymax=q_hi)); pk_pts <- p_df[p_df$Horizon==p_df$Peak_H,]; hl_pts <- p_df[p_df$Horizon==p_df$HalfLife_H,]; write.table(st_df, "Output_20260929/05_pvar_irf_stats.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8")
pdf("Output_20260929/05_pvar_irf_resilience.pdf", width=16, height=8.5); print(ggplot() + geom_ribbon(data=r_band, aes(x=Horizon, ymin=ymin, ymax=ymax), fill="gray80", alpha=0.45) + geom_area(data=p_df, aes(x=Horizon, y=Cum_IRF*0.25, fill=Dir_Group), alpha=0.22) + geom_line(data=r_df, aes(x=Horizon, y=IRF, group=Scope), color="gray55", linewidth=0.35, alpha=0.6) + geom_hline(yintercept=0, color="black", linewidth=0.4) + geom_hline(yintercept=c(-0.15, 0.15), color="#d7191c", linetype="dashed", linewidth=0.4) + geom_line(data=p_df, aes(x=Horizon, y=IRF, color=Dir_Group), linewidth=1.2) + geom_point(data=pk_pts, aes(x=Horizon, y=IRF), color="#00ffff", fill="black", shape=23, size=3.2, stroke=1) + geom_point(data=hl_pts, aes(x=Horizon, y=IRF), color="#00ff00", fill="black", shape=21, size=2.8, stroke=1) + facet_wrap(~Pair, ncol=4, scales="free_y") + scale_color_manual(values=c("1_Post-Dis"="#d7191c", "2_Pre-Dis:"="#2b83ba"), labels=c("Post-Dis (Disease Shock -> Crisis)","Pre-Dis (Crisis Shock -> Disease)"), name="Causal Regime") + scale_fill_manual(values=c("1_Post-Dis"="#fdae61", "2_Pre-Dis:"="#abdda4"), labels=c("Post-Dis Cumulative Hysteresis","Pre-Dis Cumulative Hysteresis"), name="Hysteresis Load") + scale_x_continuous(breaks=seq(0,15,by=3), expand=c(0.02,0.02)) + labs(title="Panel VAR Orthogonalized Impulse Response Functions (IRF): Epidemic (Dis), Economic Famine (Eco), and Rebellion/Unrest (Soc/Pol)", subtitle="Bold Line: Panel FE IRF | Gray Lines/Band: 10 Regional Trajectories & Envelope | Shaded Area: Scaled Cumulative Hysteresis | Diamond (Cyan): Peak Crisis | Circle (Green): Half-Life Recovery | Red Dashed: Catastrophe Threshold", x="Horizon after Structural Shock (Chronological Volume Lags: h = 0 to 15)", y="Orthogonalized Impulse Response (SD Units)") + theme_minimal() + theme(strip.text=element_text(face="bold", size=9.5), panel.grid.minor=element_blank(), legend.position="bottom")); dev.off()

################################################################################################
#Module 06. Regional Sen's Slope, Hurst Exponent, and Systemic Immunity Degradation (Dis Only)
################################################################################################
library(ggplot2); library(stringr); df$vol <- substr(df$id,1,7); df$Dis <- str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂"); regs <- c("JJ","JL","GS","CC","GG","Seoul","GW","HH","PA","HG"); d_mat <- rowsum((as.matrix(df[,regs])>0)*df$Dis, df$vol)
s_mat <- as.matrix(stats::filter(log1p(d_mat), rep(1/11,11), sides=2)); s_mat[is.na(s_mat)] <- 0; W <- diag(0.6,10); W[abs(row(W)-col(W))==1] <- 0.2; z_mat <- s_mat%*%W; colnames(z_mat) <- regs; rownames(z_mat) <- rownames(d_mat); n <- nrow(z_mat); win <- 45
yr_v <- c(1392,1399,1401,1418,1450,1452,1455,1468,1469,1494,1506,1544,1545,1567,1608,1623,1649,1659,1674,1720,1724,1776,1800,1834,1849,1863)[match(substr(rownames(z_mat),2,2),letters)] + ifelse(substr(rownames(z_mat),2,3)=="zb",44,0) + pmax(0,as.numeric(substr(rownames(z_mat),6,7))-1); yr_v[is.na(yr_v)] <- round(seq(1392,1894,length.out=n))[is.na(yr_v)]
tr_list <- list(); st_list <- list(); idx_t <- 1; for(i in seq_along(regs)) { y <- z_mat[,i] + seq(1e-6,1e-5,length.out=n); slp_all <- outer(y,y,"-")/outer(1:n,1:n,"-"); sen_all <- median(slp_all[lower.tri(slp_all)],na.rm=TRUE); int_all <- median(y - sen_all*(1:n),na.rm=TRUE); sc_v <- c(16,32,64,128); rs_v <- numeric(4); for(k in 1:4) { m_k <- sc_v[k]; nb <- floor(n/m_k); rs_b <- numeric(nb); for(b in 1:nb) { seg <- y[((b-1)*m_k+1):(b*m_k)]; dev <- cumsum(seg-mean(seg)); rs_b[b] <- (max(dev)-min(dev))/(sd(seg)+1e-9) }; rs_v[k] <- mean(rs_b) }; hurst_all <- lm.fit(cbind(1,log(sc_v)),log(rs_v+1e-9))$coefficients[2]; h_roll <- rep(0.5,n); q_roll <- rep(0,n); for(t in 1:n) { id_w <- max(1,t-win+1):min(n,t+win); y_w <- y[id_w]; m_w <- length(y_w); dev_w <- cumsum(y_w-mean(y_w)); h_roll[t] <- min(0.99,max(0.1,log((max(dev_w)-min(dev_w))/(sd(y_w)+1e-9)+1e-9)/log(m_w))); slp_w <- outer(y_w,y_w,"-")/outer(1:m_w,1:m_w,"-"); q_roll[t] <- median(slp_w[lower.tri(slp_w)],na.rm=TRUE) }; idi_v <- pmax(0, (h_roll-0.5)*1.2 + scale(q_roll)[,1]*0.15 + 0.25); sen_line <- pmax(0, int_all + sen_all*(1:n)); tr_list[[i]] <- data.frame(Region=regs[i], t_idx=1:n, Year=yr_v, Dis_Level=y, Hurst_Roll=h_roll, Sen_Roll_Scaled=q_roll*150+0.5, Sen_Trend=sen_line/max(y+1e-9)*0.8, IDI=idi_v, stringsAsFactors=FALSE); st_list[[i]] <- data.frame(Region=regs[i], Full_Sens_Slope_100Vol=round(sen_all*100,4), Sens_Intercept=round(int_all,4), Full_Hurst_Exp=round(hurst_all,4), Mean_Roll_Hurst=round(mean(h_roll),4), Max_Roll_Hurst=round(max(h_roll),4), Early_IDI_Mean=round(mean(idi_v[1:round(n/3)]),4), Late_IDI_Mean=round(mean(idi_v[round(2*n/3):n]),4), Immunity_Loss_Ratio=round(mean(idi_v[round(2*n/3):n])/(mean(idi_v[1:round(n/3)])+1e-9),3), Peak_Degradation_Year=yr_v[which.max(idi_v)], Immunity_Regime=ifelse(hurst_all>=0.65 & sen_all>0,"Severe_Immunity_Exhaustion",ifelse(hurst_all>=0.55,"Chronic_Endemic_Persistence","Resilient_Sporadic")), stringsAsFactors=FALSE) }
tr_df <- do.call(rbind, tr_list); st_df <- do.call(rbind, st_list); tr_df$Region <- factor(tr_df$Region, levels=regs); write.table(st_df, "Output_20260929/06_dis_sens_hurst_stats.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8"); idx_x <- seq(1, n, by=25)
pdf("Output_20260929/06_dis_immunity_degradation.pdf", width=16, height=9); print(ggplot(tr_df, aes(x=t_idx)) + geom_area(aes(y=IDI, fill="Immunity Degradation Index (IDI)"), alpha=0.35) + geom_hline(yintercept=0.5, color="gray25", linetype="dashed", linewidth=0.45) + geom_line(aes(y=Sen_Trend, color="Full-Period Sen's Trendline"), linetype="twodash", linewidth=0.8) + geom_line(aes(y=Sen_Roll_Scaled, color="Rolling Sen's Slope (Scaled + 0.5)"), linewidth=0.65, alpha=0.85) + geom_line(aes(y=Hurst_Roll, color="Rolling Hurst Exponent (H)"), linewidth=0.95) + facet_wrap(~Region, ncol=5) + scale_color_manual(name="Trend & Memory Metrics", values=c("Rolling Hurst Exponent (H)"="#d7191c", "Rolling Sen's Slope (Scaled + 0.5)"="#2b83ba", "Full-Period Sen's Trendline"="black")) + scale_fill_manual(name="Systemic Vulnerability", values=c("Immunity Degradation Index (IDI)"="#7b3294")) + scale_x_continuous(breaks=idx_x, labels=yr_v[idx_x], expand=c(0.01,0.01)) + scale_y_continuous(limits=c(0,1.25), breaks=seq(0,1.2,by=0.25)) + labs(title="Spatio-Temporal Trajectory of Sen's Slope, Hurst Exponent (H), and Systemic Immunity Degradation (Dis Only)", subtitle="Red Line: Rolling Hurst Exponent (H > 0.5 = Long-Memory Persistence) | Blue Line: Rolling Sen's Slope | Black Dash: Full-Period Sen's Trend | Purple Shaded Area: Immunity Degradation Index (IDI)", x="Chronological Year (Joseon Dynasty)", y="Hurst Exponent (H) / Scaled Sen's Slope & Immunity Degradation Load") + theme_minimal() + theme(axis.text.x=element_text(angle=90, hjust=1, size=6.5), strip.text=element_text(face="bold", size=11), panel.grid.minor=element_blank(), legend.position="bottom")); dev.off()

################################################################################################
#Module 07. Spatio-temporal Difference-in-Differences (DiD) and Immunity Degradation (Dis Only)
################################################################################################
library(ggplot2); library(stringr); df$vol <- substr(df$id,1,7); df$Dis <- str_count(df$t,"疫病|溫疫|疾疫|痘瘡|霍亂"); regs <- c("JJ","JL","GS","CC","GG","Seoul","GW","HH","PA","HG"); d_mat <- rowsum((as.matrix(df[,regs])>0)*df$Dis, df$vol)
s_mat <- as.matrix(stats::filter(log1p(d_mat), rep(1/11,11), sides=2)); s_mat[is.na(s_mat)] <- 0; W <- diag(0.6,10); W[abs(row(W)-col(W))==1] <- 0.2; z_mat <- s_mat%*%W; colnames(z_mat) <- regs; rownames(z_mat) <- rownames(d_mat); n <- nrow(z_mat); win <- 30
yr_v <- c(1392,1399,1401,1418,1450,1452,1455,1468,1469,1494,1506,1544,1545,1567,1608,1623,1649,1659,1674,1720,1724,1776,1800,1834,1849,1863)[match(substr(rownames(z_mat),2,2),letters)] + ifelse(substr(rownames(z_mat),2,3)=="zb",44,0) + pmax(0,as.numeric(substr(rownames(z_mat),6,7))-1); yr_v[is.na(yr_v)] <- round(seq(1392,1894,length.out=n))[is.na(yr_v)]
c_base <- numeric(n); for(t in 1:n) { c_base[t] <- quantile(z_mat[t,], 0.2) }; t_brk <- which(yr_v>=1592)[1]; if(is.na(t_brk)) t_brk <- round(n*0.4); pre_id <- 1:(t_brk-1); post_id <- t_brk:n; did_list <- list(); st_list <- list()
for(i in seq_along(regs)) { y <- z_mat[,i]; y_cf <- mean(y[pre_id]) + (c_base - mean(c_base[pre_id])); did_dyn <- (y - mean(y[pre_id])) - (c_base - mean(c_base[pre_id])); r_did <- numeric(n); for(t in 1:n) { id1 <- max(1,t-win):t; id2 <- t:min(n,t+win); r_did[t] <- (mean(y[id2])-mean(y[id1])) - (mean(c_base[id2])-mean(c_base[id1])) }; Y_reg <- c(y, c_base); tr_v <- rep(c(1,0), each=n); po_v <- rep(ifelse(1:n>=t_brk,1,0), 2); did_v <- tr_v*po_v; X_reg <- cbind(1, tr_v, po_v, did_v); fit <- lm.fit(X_reg, Y_reg); b_did <- fit$coefficients[4]; se_did <- sqrt(sum(fit$residuals^2)/(2*n-4)*solve(t(X_reg)%*%X_reg)[4,4]+1e-9); t_val <- b_did/se_did; p_val <- 2*pt(abs(t_val), df=2*n-4, lower.tail=FALSE); step_line <- ifelse(1:n<t_brk, mean(y[pre_id]), mean(y[pre_id])+b_did); deg_load <- pmax(0, did_dyn); did_list[[i]] <- data.frame(Region=regs[i], t_idx=1:n, Year=yr_v, Observed=y, Counterfactual=pmax(0,y_cf), DiD_Effect=did_dyn, Rolling_DiD=r_did, Step_DiD=pmax(0,step_line), Deg_Upper=pmax(y,pmax(0,y_cf)), Deg_Lower=pmax(0,y_cf), stringsAsFactors=FALSE); st_list[[i]] <- data.frame(Region=regs[i], Pre_Mean_Dis=round(mean(y[pre_id]),3), Post_Mean_Dis=round(mean(y[post_id]),3), Counterfactual_Post=round(mean(y_cf[post_id]),3), Canonical_DiD_Beta=round(b_did,4), DiD_SE=round(se_did,4), DiD_t_Stat=round(t_val,3), DiD_P_Val=round(p_val,5), Max_Dynamic_DiD=round(max(did_dyn),3), Peak_DiD_Year=yr_v[which.max(did_dyn)], Cum_Immunity_Deficit=round(sum(deg_load),2), Immunity_Status=ifelse(b_did>0.05 & p_val<0.05, "Structural_Immunity_Collapse", ifelse(b_did>0, "Moderate_Degradation", "Resilient_Buffered")), stringsAsFactors=FALSE) }
did_df <- do.call(rbind, did_list); st_df <- do.call(rbind, st_list); did_df$Region <- factor(did_df$Region, levels=regs); write.table(st_df, "Output_20260929/07_dis_did_stats.txt", sep="\t", row.names=FALSE, fileEncoding="UTF-8"); idx_x <- seq(1, n, by=25)
pdf("Output_20260929/07_dis_did_immunity.pdf", width=16, height=9); print(ggplot(did_df, aes(x=t_idx)) + geom_ribbon(aes(ymin=Deg_Lower, ymax=Deg_Upper, fill="DiD Immunity Degradation Wedge (Excess Dis)"), alpha=0.38) + geom_vline(xintercept=t_brk, color="gray20", linetype="dotted", linewidth=0.55) + geom_line(aes(y=Counterfactual, color="DiD Counterfactual Baseline (Intact Immunity)"), linetype="dashed", linewidth=0.7) + geom_line(aes(y=Observed, color="Observed Epidemic Intensity (Dis)"), linewidth=0.85) + geom_line(aes(y=Step_DiD, color="Canonical Pre/Post DiD Level Shift"), linetype="twodash", linewidth=0.85) + geom_line(aes(y=Rolling_DiD+mean(Observed), color="Rolling Window Local DiD Surge"), linewidth=0.55, alpha=0.8) + facet_wrap(~Region, ncol=5) + scale_color_manual(name="DiD Trajectories", values=c("Observed Epidemic Intensity (Dis)"="#d7191c", "DiD Counterfactual Baseline (Intact Immunity)"="#2b83ba", "Canonical Pre/Post DiD Level Shift"="black", "Rolling Window Local DiD Surge"="#fdae61")) + scale_fill_manual(name="Systemic Vulnerability", values=c("DiD Immunity Degradation Wedge (Excess Dis)"="#7b3294")) + scale_x_continuous(breaks=idx_x, labels=yr_v[idx_x], expand=c(0.01,0.01)) + labs(title="Spatio-Temporal Difference-in-Differences (DiD) Trajectory and Systemic Immunity Degradation (Dis Only)", subtitle="Red: Observed Dis | Blue Dashed: DiD Counterfactual (Intact Immunity) | Purple Wedge: Excess Epidemic Load (DiD Immunity Collapse) | Black Dash: Pre/Post-1592 DiD Shift", x="Chronological Year (Joseon Dynasty)", y="Epidemic Intensity & DiD Counterfactual Gap") + theme_minimal() + theme(axis.text.x=element_text(angle=90, hjust=1, size=6.5), strip.text=element_text(face="bold", size=11), panel.grid.minor=element_blank(), legend.position="bottom")); dev.off()











