setwd("G:/내 드라이브/Rrunning/HW014/")
library(data.table); library(dplyr); library(readxl)
library(survival); library(survminer); library(ggplot2)
library(stringr)
rm(list=ls())
make.unique.2 = function(x, sep='.'){ ave(x, x, FUN=function(a){if(length(a) > 1){paste(a, 1:length(a), sep=sep)} else {a}}) }
options(tempdir = "C:/Temp")
Sys.setenv(TMPDIR = tempdir, TEMP = tempdir, TMP = tempdir)
########################################################################################################################################################################################################################################################################################
#Module 01
SELECT_LIST1 <- c("bcr_patient_barcode","days_to_birth","gender","days_to_last_followup","days_to_death","vital_status");                                COLNAME_LIST1 <- c("ID","Age","Sex","FU","F2","Surv")
SELECT_LIST2 <- c("bcr_patient_barcode","days_to_birth","gender","days_to_last_followup","days_to_death","vital_status","stage_event_pathologic_stage"); COLNAME_LIST2 <- c("ID","Age","Sex","FU","F2","Surv","Stage")
SELECT_LIST3 <- c("bcr_patient_barcode","days_to_birth","gender","days_to_last_followup","days_to_death","vital_status","stage_event_clinical_stage"  ); COLNAME_LIST3 <- c("ID","Age","Sex","FU","F2","Surv","Stage")
SELECT_LIST4 <- c("bcr_patient_barcode","days_to_birth","gender","days_to_last_followup","days_to_death","vital_status","stage_event_masaoka_stage"   ); COLNAME_LIST4 <- c("ID","Age","Sex","FU","F2","Surv","Stage")

ACC__c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_ACC_Cln.txt.gz',  header = TRUE, sep = '	')), SELECT_LIST2); colnames(ACC__c) <- COLNAME_LIST2; ACC__c$Sex <- substr(ACC__c$Sex,1,1); ACC__c$Age <- -round(ACC__c$Age/365,0); ACC__c$FU <- ifelse(is.na(ACC__c$FU),ACC__c$F2,ACC__c$FU); ACC__c$F2 <- NULL; ACC__c$Surv <- ifelse(ACC__c$Surv=="Alive",1,2); ACC__c <- ACC__c[complete.cases(ACC__c), ]; ACC__c$ID <- gsub("\\-","_",ACC__c$ID)
BLCA_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_BLCA_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(BLCA_c) <- COLNAME_LIST2; BLCA_c$Sex <- substr(BLCA_c$Sex,1,1); BLCA_c$Age <- -round(BLCA_c$Age/365,0); BLCA_c$FU <- ifelse(is.na(BLCA_c$FU),BLCA_c$F2,BLCA_c$FU); BLCA_c$F2 <- NULL; BLCA_c$Surv <- ifelse(BLCA_c$Surv=="Alive",1,2); BLCA_c <- BLCA_c[complete.cases(BLCA_c), ]; BLCA_c$ID <- gsub("\\-","_",BLCA_c$ID)
BRCA_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_BRCA_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(BRCA_c) <- COLNAME_LIST2; BRCA_c$Sex <- substr(BRCA_c$Sex,1,1); BRCA_c$Age <- -round(BRCA_c$Age/365,0); BRCA_c$FU <- ifelse(is.na(BRCA_c$FU),BRCA_c$F2,BRCA_c$FU); BRCA_c$F2 <- NULL; BRCA_c$Surv <- ifelse(BRCA_c$Surv=="Alive",1,2); BRCA_c <- BRCA_c[complete.cases(BRCA_c), ]; BRCA_c$ID <- gsub("\\-","_",BRCA_c$ID)
CESC_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_CESC_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST3); colnames(CESC_c) <- COLNAME_LIST3; CESC_c$Sex <- substr(CESC_c$Sex,1,1); CESC_c$Age <- -round(CESC_c$Age/365,0); CESC_c$FU <- ifelse(is.na(CESC_c$FU),CESC_c$F2,CESC_c$FU); CESC_c$F2 <- NULL; CESC_c$Surv <- ifelse(CESC_c$Surv=="Alive",1,2); CESC_c <- CESC_c[complete.cases(CESC_c), ]; CESC_c$ID <- gsub("\\-","_",CESC_c$ID)
CHOL_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_CHOL_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(CHOL_c) <- COLNAME_LIST2; CHOL_c$Sex <- substr(CHOL_c$Sex,1,1); CHOL_c$Age <- -round(CHOL_c$Age/365,0); CHOL_c$FU <- ifelse(is.na(CHOL_c$FU),CHOL_c$F2,CHOL_c$FU); CHOL_c$F2 <- NULL; CHOL_c$Surv <- ifelse(CHOL_c$Surv=="Alive",1,2); CHOL_c <- CHOL_c[complete.cases(CHOL_c), ]; CHOL_c$ID <- gsub("\\-","_",CHOL_c$ID)
COAD_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_COAD_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(COAD_c) <- COLNAME_LIST2; COAD_c$Sex <- substr(COAD_c$Sex,1,1); COAD_c$Age <- -round(COAD_c$Age/365,0); COAD_c$FU <- ifelse(is.na(COAD_c$FU),COAD_c$F2,COAD_c$FU); COAD_c$F2 <- NULL; COAD_c$Surv <- ifelse(COAD_c$Surv=="Alive",1,2); COAD_c <- COAD_c[complete.cases(COAD_c), ]; COAD_c$ID <- gsub("\\-","_",COAD_c$ID)
DLBC_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_DLBC_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST3); colnames(DLBC_c) <- COLNAME_LIST3; DLBC_c$Sex <- substr(DLBC_c$Sex,1,1); DLBC_c$Age <- -round(DLBC_c$Age/365,0); DLBC_c$FU <- ifelse(is.na(DLBC_c$FU),DLBC_c$F2,DLBC_c$FU); DLBC_c$F2 <- NULL; DLBC_c$Surv <- ifelse(DLBC_c$Surv=="Alive",1,2); DLBC_c <- DLBC_c[complete.cases(DLBC_c), ]; DLBC_c$ID <- gsub("\\-","_",DLBC_c$ID)
ESCA_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_ESCA_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(ESCA_c) <- COLNAME_LIST2; ESCA_c$Sex <- substr(ESCA_c$Sex,1,1); ESCA_c$Age <- -round(ESCA_c$Age/365,0); ESCA_c$FU <- ifelse(is.na(ESCA_c$FU),ESCA_c$F2,ESCA_c$FU); ESCA_c$F2 <- NULL; ESCA_c$Surv <- ifelse(ESCA_c$Surv=="Alive",1,2); ESCA_c <- ESCA_c[complete.cases(ESCA_c), ]; ESCA_c$ID <- gsub("\\-","_",ESCA_c$ID)
GBM__c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_GBM_Cln.txt.gz',  header = TRUE, sep = '	')), SELECT_LIST1); colnames(GBM__c) <- COLNAME_LIST1; GBM__c$Sex <- substr(GBM__c$Sex,1,1); GBM__c$Age <- -round(GBM__c$Age/365,0); GBM__c$FU <- ifelse(is.na(GBM__c$FU),GBM__c$F2,GBM__c$FU); GBM__c$F2 <- NULL; GBM__c$Surv <- ifelse(GBM__c$Surv=="Alive",1,2); GBM__c <- GBM__c[complete.cases(GBM__c), ]; GBM__c$ID <- gsub("\\-","_",GBM__c$ID)
HNSC_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_HNSC_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(HNSC_c) <- COLNAME_LIST2; HNSC_c$Sex <- substr(HNSC_c$Sex,1,1); HNSC_c$Age <- -round(HNSC_c$Age/365,0); HNSC_c$FU <- ifelse(is.na(HNSC_c$FU),HNSC_c$F2,HNSC_c$FU); HNSC_c$F2 <- NULL; HNSC_c$Surv <- ifelse(HNSC_c$Surv=="Alive",1,2); HNSC_c <- HNSC_c[complete.cases(HNSC_c), ]; HNSC_c$ID <- gsub("\\-","_",HNSC_c$ID)
KICH_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_KICH_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(KICH_c) <- COLNAME_LIST2; KICH_c$Sex <- substr(KICH_c$Sex,1,1); KICH_c$Age <- -round(KICH_c$Age/365,0); KICH_c$FU <- ifelse(is.na(KICH_c$FU),KICH_c$F2,KICH_c$FU); KICH_c$F2 <- NULL; KICH_c$Surv <- ifelse(KICH_c$Surv=="Alive",1,2); KICH_c <- KICH_c[complete.cases(KICH_c), ]; KICH_c$ID <- gsub("\\-","_",KICH_c$ID)
KIRC_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_KIRC_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(KIRC_c) <- COLNAME_LIST2; KIRC_c$Sex <- substr(KIRC_c$Sex,1,1); KIRC_c$Age <- -round(KIRC_c$Age/365,0); KIRC_c$FU <- ifelse(is.na(KIRC_c$FU),KIRC_c$F2,KIRC_c$FU); KIRC_c$F2 <- NULL; KIRC_c$Surv <- ifelse(KIRC_c$Surv=="Alive",1,2); KIRC_c <- KIRC_c[complete.cases(KIRC_c), ]; KIRC_c$ID <- gsub("\\-","_",KIRC_c$ID)
KIRP_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_KIRP_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(KIRP_c) <- COLNAME_LIST2; KIRP_c$Sex <- substr(KIRP_c$Sex,1,1); KIRP_c$Age <- -round(KIRP_c$Age/365,0); KIRP_c$FU <- ifelse(is.na(KIRP_c$FU),KIRP_c$F2,KIRP_c$FU); KIRP_c$F2 <- NULL; KIRP_c$Surv <- ifelse(KIRP_c$Surv=="Alive",1,2); KIRP_c <- KIRP_c[complete.cases(KIRP_c), ]; KIRP_c$ID <- gsub("\\-","_",KIRP_c$ID)
LAML_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_LAML_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST1); colnames(LAML_c) <- COLNAME_LIST1; LAML_c$Sex <- substr(LAML_c$Sex,1,1); LAML_c$Age <- -round(LAML_c$Age/365,0); LAML_c$FU <- ifelse(is.na(LAML_c$FU),LAML_c$F2,LAML_c$FU); LAML_c$F2 <- NULL; LAML_c$Surv <- ifelse(LAML_c$Surv=="Alive",1,2); LAML_c <- LAML_c[complete.cases(LAML_c), ]; LAML_c$ID <- gsub("\\-","_",LAML_c$ID)
LGG__c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_LGG_Cln.txt.gz',  header = TRUE, sep = '	')), SELECT_LIST1); colnames(LGG__c) <- COLNAME_LIST1; LGG__c$Sex <- substr(LGG__c$Sex,1,1); LGG__c$Age <- -round(LGG__c$Age/365,0); LGG__c$FU <- ifelse(is.na(LGG__c$FU),LGG__c$F2,LGG__c$FU); LGG__c$F2 <- NULL; LGG__c$Surv <- ifelse(LGG__c$Surv=="Alive",1,2); LGG__c <- LGG__c[complete.cases(LGG__c), ]; LGG__c$ID <- gsub("\\-","_",LGG__c$ID)
LIHC_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_LIHC_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(LIHC_c) <- COLNAME_LIST2; LIHC_c$Sex <- substr(LIHC_c$Sex,1,1); LIHC_c$Age <- -round(LIHC_c$Age/365,0); LIHC_c$FU <- ifelse(is.na(LIHC_c$FU),LIHC_c$F2,LIHC_c$FU); LIHC_c$F2 <- NULL; LIHC_c$Surv <- ifelse(LIHC_c$Surv=="Alive",1,2); LIHC_c <- LIHC_c[complete.cases(LIHC_c), ]; LIHC_c$ID <- gsub("\\-","_",LIHC_c$ID)
LUAD_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_LUAD_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(LUAD_c) <- COLNAME_LIST2; LUAD_c$Sex <- substr(LUAD_c$Sex,1,1); LUAD_c$Age <- -round(LUAD_c$Age/365,0); LUAD_c$FU <- ifelse(is.na(LUAD_c$FU),LUAD_c$F2,LUAD_c$FU); LUAD_c$F2 <- NULL; LUAD_c$Surv <- ifelse(LUAD_c$Surv=="Alive",1,2); LUAD_c <- LUAD_c[complete.cases(LUAD_c), ]; LUAD_c$ID <- gsub("\\-","_",LUAD_c$ID)
LUSC_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_LUSC_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(LUSC_c) <- COLNAME_LIST2; LUSC_c$Sex <- substr(LUSC_c$Sex,1,1); LUSC_c$Age <- -round(LUSC_c$Age/365,0); LUSC_c$FU <- ifelse(is.na(LUSC_c$FU),LUSC_c$F2,LUSC_c$FU); LUSC_c$F2 <- NULL; LUSC_c$Surv <- ifelse(LUSC_c$Surv=="Alive",1,2); LUSC_c <- LUSC_c[complete.cases(LUSC_c), ]; LUSC_c$ID <- gsub("\\-","_",LUSC_c$ID)
MESO_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_MESO_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(MESO_c) <- COLNAME_LIST2; MESO_c$Sex <- substr(MESO_c$Sex,1,1); MESO_c$Age <- -round(MESO_c$Age/365,0); MESO_c$FU <- ifelse(is.na(MESO_c$FU),MESO_c$F2,MESO_c$FU); MESO_c$F2 <- NULL; MESO_c$Surv <- ifelse(MESO_c$Surv=="Alive",1,2); MESO_c <- MESO_c[complete.cases(MESO_c), ]; MESO_c$ID <- gsub("\\-","_",MESO_c$ID)
OV___c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_OV_Cln.txt.gz',   header = TRUE, sep = '	')), SELECT_LIST1); colnames(OV___c) <- COLNAME_LIST1; OV___c$Sex <- substr(OV___c$Sex,1,1); OV___c$Age <- -round(OV___c$Age/365,0); OV___c$FU <- ifelse(is.na(OV___c$FU),OV___c$F2,OV___c$FU); OV___c$F2 <- NULL; OV___c$Surv <- ifelse(OV___c$Surv=="Alive",1,2); OV___c <- OV___c[complete.cases(OV___c), ]; OV___c$ID <- gsub("\\-","_",OV___c$ID)
PAAD_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_PAAD_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(PAAD_c) <- COLNAME_LIST2; PAAD_c$Sex <- substr(PAAD_c$Sex,1,1); PAAD_c$Age <- -round(PAAD_c$Age/365,0); PAAD_c$FU <- ifelse(is.na(PAAD_c$FU),PAAD_c$F2,PAAD_c$FU); PAAD_c$F2 <- NULL; PAAD_c$Surv <- ifelse(PAAD_c$Surv=="Alive",1,2); PAAD_c <- PAAD_c[complete.cases(PAAD_c), ]; PAAD_c$ID <- gsub("\\-","_",PAAD_c$ID)
PCPG_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_PCPG_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST1); colnames(PCPG_c) <- COLNAME_LIST1; PCPG_c$Sex <- substr(PCPG_c$Sex,1,1); PCPG_c$Age <- -round(PCPG_c$Age/365,0); PCPG_c$FU <- ifelse(is.na(PCPG_c$FU),PCPG_c$F2,PCPG_c$FU); PCPG_c$F2 <- NULL; PCPG_c$Surv <- ifelse(PCPG_c$Surv=="Alive",1,2); PCPG_c <- PCPG_c[complete.cases(PCPG_c), ]; PCPG_c$ID <- gsub("\\-","_",PCPG_c$ID)
PRAD_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_PRAD_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST1); colnames(PRAD_c) <- COLNAME_LIST1; PRAD_c$Sex <- substr(PRAD_c$Sex,1,1); PRAD_c$Age <- -round(PRAD_c$Age/365,0); PRAD_c$FU <- ifelse(is.na(PRAD_c$FU),PRAD_c$F2,PRAD_c$FU); PRAD_c$F2 <- NULL; PRAD_c$Surv <- ifelse(PRAD_c$Surv=="Alive",1,2); PRAD_c <- PRAD_c[complete.cases(PRAD_c), ]; PRAD_c$ID <- gsub("\\-","_",PRAD_c$ID)
READ_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_READ_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(READ_c) <- COLNAME_LIST2; READ_c$Sex <- substr(READ_c$Sex,1,1); READ_c$Age <- -round(READ_c$Age/365,0); READ_c$FU <- ifelse(is.na(READ_c$FU),READ_c$F2,READ_c$FU); READ_c$F2 <- NULL; READ_c$Surv <- ifelse(READ_c$Surv=="Alive",1,2); READ_c <- READ_c[complete.cases(READ_c), ]; READ_c$ID <- gsub("\\-","_",READ_c$ID)
SKCM_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_SKCM_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(SKCM_c) <- COLNAME_LIST2; SKCM_c$Sex <- substr(SKCM_c$Sex,1,1); SKCM_c$Age <- -round(SKCM_c$Age/365,0); SKCM_c$FU <- ifelse(is.na(SKCM_c$FU),SKCM_c$F2,SKCM_c$FU); SKCM_c$F2 <- NULL; SKCM_c$Surv <- ifelse(SKCM_c$Surv=="Alive",1,2); SKCM_c <- SKCM_c[complete.cases(SKCM_c), ]; SKCM_c$ID <- gsub("\\-","_",SKCM_c$ID)
STAD_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_STAD_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(STAD_c) <- COLNAME_LIST2; STAD_c$Sex <- substr(STAD_c$Sex,1,1); STAD_c$Age <- -round(STAD_c$Age/365,0); STAD_c$FU <- ifelse(is.na(STAD_c$FU),STAD_c$F2,STAD_c$FU); STAD_c$F2 <- NULL; STAD_c$Surv <- ifelse(STAD_c$Surv=="Alive",1,2); STAD_c <- STAD_c[complete.cases(STAD_c), ]; STAD_c$ID <- gsub("\\-","_",STAD_c$ID)
TGCT_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_TGCT_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(TGCT_c) <- COLNAME_LIST2; TGCT_c$Sex <- substr(TGCT_c$Sex,1,1); TGCT_c$Age <- -round(TGCT_c$Age/365,0); TGCT_c$FU <- ifelse(is.na(TGCT_c$FU),TGCT_c$F2,TGCT_c$FU); TGCT_c$F2 <- NULL; TGCT_c$Surv <- ifelse(TGCT_c$Surv=="Alive",1,2); TGCT_c <- TGCT_c[complete.cases(TGCT_c), ]; TGCT_c$ID <- gsub("\\-","_",TGCT_c$ID)
THCA_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_THCA_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST2); colnames(THCA_c) <- COLNAME_LIST2; THCA_c$Sex <- substr(THCA_c$Sex,1,1); THCA_c$Age <- -round(THCA_c$Age/365,0); THCA_c$FU <- ifelse(is.na(THCA_c$FU),THCA_c$F2,THCA_c$FU); THCA_c$F2 <- NULL; THCA_c$Surv <- ifelse(THCA_c$Surv=="Alive",1,2); THCA_c <- THCA_c[complete.cases(THCA_c), ]; THCA_c$ID <- gsub("\\-","_",THCA_c$ID)
THYM_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_THYM_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST4); colnames(THYM_c) <- COLNAME_LIST4; THYM_c$Sex <- substr(THYM_c$Sex,1,1); THYM_c$Age <- -round(THYM_c$Age/365,0); THYM_c$FU <- ifelse(is.na(THYM_c$FU),THYM_c$F2,THYM_c$FU); THYM_c$F2 <- NULL; THYM_c$Surv <- ifelse(THYM_c$Surv=="Alive",1,2); THYM_c <- THYM_c[complete.cases(THYM_c), ]; THYM_c$ID <- gsub("\\-","_",THYM_c$ID)
UCEC_c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_UCEC_Cln.txt.gz', header = TRUE, sep = '	')), SELECT_LIST3); colnames(UCEC_c) <- COLNAME_LIST3; UCEC_c$Sex <- substr(UCEC_c$Sex,1,1); UCEC_c$Age <- -round(UCEC_c$Age/365,0); UCEC_c$FU <- ifelse(is.na(UCEC_c$FU),UCEC_c$F2,UCEC_c$FU); UCEC_c$F2 <- NULL; UCEC_c$Surv <- ifelse(UCEC_c$Surv=="Alive",1,2); UCEC_c <- UCEC_c[complete.cases(UCEC_c), ]; UCEC_c$ID <- gsub("\\-","_",UCEC_c$ID)
UCS__c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_UCS_Cln.txt.gz',  header = TRUE, sep = '	')), SELECT_LIST3); colnames(UCS__c) <- COLNAME_LIST3; UCS__c$Sex <- substr(UCS__c$Sex,1,1); UCS__c$Age <- -round(UCS__c$Age/365,0); UCS__c$FU <- ifelse(is.na(UCS__c$FU),UCS__c$F2,UCS__c$FU); UCS__c$F2 <- NULL; UCS__c$Surv <- ifelse(UCS__c$Surv=="Alive",1,2); UCS__c <- UCS__c[complete.cases(UCS__c), ]; UCS__c$ID <- gsub("\\-","_",UCS__c$ID)
UVM__c <- dplyr::select(as.data.frame(fread('G:/내 드라이브/Rrunning/TCGA/01_Cln/data_UVM_Cln.txt.gz',  header = TRUE, sep = '	')), SELECT_LIST2); colnames(UVM__c) <- COLNAME_LIST2; UVM__c$Sex <- substr(UVM__c$Sex,1,1); UVM__c$Age <- -round(UVM__c$Age/365,0); UVM__c$FU <- ifelse(is.na(UVM__c$FU),UVM__c$F2,UVM__c$FU); UVM__c$F2 <- NULL; UVM__c$Surv <- ifelse(UVM__c$Surv=="Alive",1,2); UVM__c <- UVM__c[complete.cases(UVM__c), ]; UVM__c$ID <- gsub("\\-","_",UVM__c$ID)

########################################################################################################################################################################################################################################################################################
#Module 02
ACC__Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-ACC-Methyl_450k.txt.gz" , header = TRUE, sep = "\t")); rownames(ACC__Met) <- ACC__Met$`Composite Element REF`; ACC__Met <- ACC__Met[,-1]; ACC__Met <- dplyr::select(ACC__Met, contains("01A")); colnames(ACC__Met) <- substr(colnames(ACC__Met),1,12)
BLCA_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-BLCA-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(BLCA_Met) <- BLCA_Met$`Composite Element REF`; BLCA_Met <- BLCA_Met[,-1]; BLCA_Met <- dplyr::select(BLCA_Met, contains("01A")); colnames(BLCA_Met) <- substr(colnames(BLCA_Met),1,12)
BRCA_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-BRCA-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(BRCA_Met) <- BRCA_Met$`Composite Element REF`; BRCA_Met <- BRCA_Met[,-1]; BRCA_Met <- dplyr::select(BRCA_Met, contains("01A")); colnames(BRCA_Met) <- substr(colnames(BRCA_Met),1,12)
CESC_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-CESC-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(CESC_Met) <- CESC_Met$`Composite Element REF`; CESC_Met <- CESC_Met[,-1]; CESC_Met <- dplyr::select(CESC_Met, contains("01A")); colnames(CESC_Met) <- substr(colnames(CESC_Met),1,12)
CHOL_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-CHOL-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(CHOL_Met) <- CHOL_Met$`Composite Element REF`; CHOL_Met <- CHOL_Met[,-1]; CHOL_Met <- dplyr::select(CHOL_Met, contains("01A")); colnames(CHOL_Met) <- substr(colnames(CHOL_Met),1,12)
COAD_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-COAD-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(COAD_Met) <- COAD_Met$`Composite Element REF`; COAD_Met <- COAD_Met[,-1]; COAD_Met <- dplyr::select(COAD_Met, contains("01A")); colnames(COAD_Met) <- substr(colnames(COAD_Met),1,12)
DLBC_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-DLBC-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(DLBC_Met) <- DLBC_Met$`Composite Element REF`; DLBC_Met <- DLBC_Met[,-1]; DLBC_Met <- dplyr::select(DLBC_Met, contains("01A")); colnames(DLBC_Met) <- substr(colnames(DLBC_Met),1,12)
ESCA_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-ESCA-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(ESCA_Met) <- ESCA_Met$`Composite Element REF`; ESCA_Met <- ESCA_Met[,-1]; ESCA_Met <- dplyr::select(ESCA_Met, contains("01A")); colnames(ESCA_Met) <- substr(colnames(ESCA_Met),1,12)
GBM__Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-GBM-Methyl_450k.txt.gz" , header = TRUE, sep = "\t")); rownames(GBM__Met) <- GBM__Met$`Composite Element REF`; GBM__Met <- GBM__Met[,-1]; GBM__Met <- dplyr::select(GBM__Met, contains("01A")); colnames(GBM__Met) <- substr(colnames(GBM__Met),1,12)
HNSC_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-HNSC-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(HNSC_Met) <- HNSC_Met$`Composite Element REF`; HNSC_Met <- HNSC_Met[,-1]; HNSC_Met <- dplyr::select(HNSC_Met, contains("01A")); colnames(HNSC_Met) <- substr(colnames(HNSC_Met),1,12)
KICH_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-KICH-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(KICH_Met) <- KICH_Met$`Composite Element REF`; KICH_Met <- KICH_Met[,-1]; KICH_Met <- dplyr::select(KICH_Met, contains("01A")); colnames(KICH_Met) <- substr(colnames(KICH_Met),1,12)
KIRC_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-KIRC-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(KIRC_Met) <- KIRC_Met$`Composite Element REF`; KIRC_Met <- KIRC_Met[,-1]; KIRC_Met <- dplyr::select(KIRC_Met, contains("01A")); colnames(KIRC_Met) <- substr(colnames(KIRC_Met),1,12)
KIRP_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-KIRP-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(KIRP_Met) <- KIRP_Met$`Composite Element REF`; KIRP_Met <- KIRP_Met[,-1]; KIRP_Met <- dplyr::select(KIRP_Met, contains("01A")); colnames(KIRP_Met) <- substr(colnames(KIRP_Met),1,12)
LAML_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-LAML-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(LAML_Met) <- LAML_Met$`Composite Element REF`; LAML_Met <- LAML_Met[,-1]; LAML_Met <- dplyr::select(LAML_Met, contains("03A")); colnames(LAML_Met) <- substr(colnames(LAML_Met),1,12)
LGG__Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-LGG-Methyl_450k.txt.gz" , header = TRUE, sep = "\t")); rownames(LGG__Met) <- LGG__Met$`Composite Element REF`; LGG__Met <- LGG__Met[,-1]; LGG__Met <- dplyr::select(LGG__Met, contains("01A")); colnames(LGG__Met) <- substr(colnames(LGG__Met),1,12)
LIHC_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-LIHC-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(LIHC_Met) <- LIHC_Met$`Composite Element REF`; LIHC_Met <- LIHC_Met[,-1]; LIHC_Met <- dplyr::select(LIHC_Met, contains("01A")); colnames(LIHC_Met) <- substr(colnames(LIHC_Met),1,12)
LUAD_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-LUAD-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(LUAD_Met) <- LUAD_Met$`Composite Element REF`; LUAD_Met <- LUAD_Met[,-1]; LUAD_Met <- dplyr::select(LUAD_Met, contains("01A")); colnames(LUAD_Met) <- substr(colnames(LUAD_Met),1,12)
LUSC_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-LUSC-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(LUSC_Met) <- LUSC_Met$`Composite Element REF`; LUSC_Met <- LUSC_Met[,-1]; LUSC_Met <- dplyr::select(LUSC_Met, contains("01A")); colnames(LUSC_Met) <- substr(colnames(LUSC_Met),1,12)
MESO_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-MESO-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(MESO_Met) <- MESO_Met$`Composite Element REF`; MESO_Met <- MESO_Met[,-1]; MESO_Met <- dplyr::select(MESO_Met, contains("01A")); colnames(MESO_Met) <- substr(colnames(MESO_Met),1,12)
OV___Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-OV-Methyl_450k.txt.gz"  , header = TRUE, sep = "\t")); rownames(OV___Met) <- OV___Met$`Composite Element REF`; OV___Met <- OV___Met[,-1]; OV___Met <- dplyr::select(OV___Met, contains("01A")); colnames(OV___Met) <- substr(colnames(OV___Met),1,12)
PAAD_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-PAAD-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(PAAD_Met) <- PAAD_Met$`Composite Element REF`; PAAD_Met <- PAAD_Met[,-1]; PAAD_Met <- dplyr::select(PAAD_Met, contains("01A")); colnames(PAAD_Met) <- substr(colnames(PAAD_Met),1,12)
PCPG_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-PCPG-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(PCPG_Met) <- PCPG_Met$`Composite Element REF`; PCPG_Met <- PCPG_Met[,-1]; PCPG_Met <- dplyr::select(PCPG_Met, contains("01A")); colnames(PCPG_Met) <- substr(colnames(PCPG_Met),1,12)
PRAD_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-PRAD-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(PRAD_Met) <- PRAD_Met$`Composite Element REF`; PRAD_Met <- PRAD_Met[,-1]; PRAD_Met <- dplyr::select(PRAD_Met, contains("01A")); colnames(PRAD_Met) <- substr(colnames(PRAD_Met),1,12)
READ_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-READ-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(READ_Met) <- READ_Met$`Composite Element REF`; READ_Met <- READ_Met[,-1]; READ_Met <- dplyr::select(READ_Met, contains("01A")); colnames(READ_Met) <- substr(colnames(READ_Met),1,12)
SKCM_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-SKCM-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(SKCM_Met) <- SKCM_Met$`Composite Element REF`; SKCM_Met <- SKCM_Met[,-1]; SKCM_Met <- dplyr::select(SKCM_Met, contains("01A")); colnames(SKCM_Met) <- substr(colnames(SKCM_Met),1,12)
STAD_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-STAD-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(STAD_Met) <- STAD_Met$`Composite Element REF`; STAD_Met <- STAD_Met[,-1]; STAD_Met <- dplyr::select(STAD_Met, contains("01A")); colnames(STAD_Met) <- substr(colnames(STAD_Met),1,12)
TGCT_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-TGCT-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(TGCT_Met) <- TGCT_Met$`Composite Element REF`; TGCT_Met <- TGCT_Met[,-1]; TGCT_Met <- dplyr::select(TGCT_Met, contains("01A")); colnames(TGCT_Met) <- substr(colnames(TGCT_Met),1,12)
THCA_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-THCA-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(THCA_Met) <- THCA_Met$`Composite Element REF`; THCA_Met <- THCA_Met[,-1]; THCA_Met <- dplyr::select(THCA_Met, contains("01A")); colnames(THCA_Met) <- substr(colnames(THCA_Met),1,12)
THYM_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-THYM-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(THYM_Met) <- THYM_Met$`Composite Element REF`; THYM_Met <- THYM_Met[,-1]; THYM_Met <- dplyr::select(THYM_Met, contains("01A")); colnames(THYM_Met) <- substr(colnames(THYM_Met),1,12)
UCEC_Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-UCEC-Methyl_450k.txt.gz", header = TRUE, sep = "\t")); rownames(UCEC_Met) <- UCEC_Met$`Composite Element REF`; UCEC_Met <- UCEC_Met[,-1]; UCEC_Met <- dplyr::select(UCEC_Met, contains("01A")); colnames(UCEC_Met) <- substr(colnames(UCEC_Met),1,12)
UCS__Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-UCS-Methyl_450k.txt.gz" , header = TRUE, sep = "\t")); rownames(UCS__Met) <- UCS__Met$`Composite Element REF`; UCS__Met <- UCS__Met[,-1]; UCS__Met <- dplyr::select(UCS__Met, contains("01A")); colnames(UCS__Met) <- substr(colnames(UCS__Met),1,12)
UVM__Met <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/21_Met/450k/TCGA-UVM-Methyl_450k.txt.gz" , header = TRUE, sep = "\t")); rownames(UVM__Met) <- UVM__Met$`Composite Element REF`; UVM__Met <- UVM__Met[,-1]; UVM__Met <- dplyr::select(UVM__Met, contains("01A")); colnames(UVM__Met) <- substr(colnames(UVM__Met),1,12)

TCGA_GENE <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/11_RNA/TCGA-CHOL_RNA-seq.txt.gz", header = TRUE, sep = "\t"))[,1:2]
TCGA_GENE$SYMBOL <- ifelse(is.na(TCGA_GENE$SYMBOL),TCGA_GENE$ENSEMBL,TCGA_GENE$SYMBOL)
TCGA_GENE$SYMBOL <- make.unique(TCGA_GENE$SYMBOL); TCGA_GENE <- TCGA_GENE[complete.cases(TCGA_GENE), ];  head(TCGA_GENE); dim(TCGA_GENE); table(duplicated(TCGA_GENE$SYMBOL))

TCGA_Exp <- as.data.frame(fread("G:/내 드라이브/Rrunning/TCGA/11_RNA/TCGA_Exp.txt.gz", header = TRUE, sep = "\t"))
rownames(TCGA_Exp) <- TCGA_Exp$V1; TCGA_Exp <- TCGA_Exp[,-1]
TCGA_Exp[1:5,1:5]; dim(TCGA_Exp) #56457,9668

COMMON_ACC__ID <- sort(Reduce(intersect, list(colnames(ACC__Met),colnames(TCGA_Exp),ACC__c$ID))); length(COMMON_ACC__ID) #  79
COMMON_BLCA_ID <- sort(Reduce(intersect, list(colnames(BLCA_Met),colnames(TCGA_Exp),BLCA_c$ID))); length(COMMON_BLCA_ID) # 403
COMMON_BRCA_ID <- sort(Reduce(intersect, list(colnames(BRCA_Met),colnames(TCGA_Exp),BRCA_c$ID))); length(COMMON_BRCA_ID) # 750
COMMON_CESC_ID <- sort(Reduce(intersect, list(colnames(CESC_Met),colnames(TCGA_Exp),CESC_c$ID))); length(COMMON_CESC_ID) # 294
COMMON_CHOL_ID <- sort(Reduce(intersect, list(colnames(CHOL_Met),colnames(TCGA_Exp),CHOL_c$ID))); length(COMMON_CHOL_ID) #  36
COMMON_COAD_ID <- sort(Reduce(intersect, list(colnames(COAD_Met),colnames(TCGA_Exp),COAD_c$ID))); length(COMMON_COAD_ID) # 286
COMMON_DLBC_ID <- sort(Reduce(intersect, list(colnames(DLBC_Met),colnames(TCGA_Exp),DLBC_c$ID))); length(COMMON_DLBC_ID) #  47
COMMON_ESCA_ID <- sort(Reduce(intersect, list(colnames(ESCA_Met),colnames(TCGA_Exp),ESCA_c$ID))); length(COMMON_ESCA_ID) # 152
COMMON_GBM__ID <- sort(Reduce(intersect, list(colnames(GBM__Met),colnames(TCGA_Exp),GBM__c$ID))); length(COMMON_GBM__ID) #  45
COMMON_HNSC_ID <- sort(Reduce(intersect, list(colnames(HNSC_Met),colnames(TCGA_Exp),HNSC_c$ID))); length(COMMON_HNSC_ID) # 494
COMMON_KICH_ID <- sort(Reduce(intersect, list(colnames(KICH_Met),colnames(TCGA_Exp),KICH_c$ID))); length(COMMON_KICH_ID) #  64
COMMON_KIRC_ID <- sort(Reduce(intersect, list(colnames(KIRC_Met),colnames(TCGA_Exp),KIRC_c$ID))); length(COMMON_KIRC_ID) # 314
COMMON_KIRP_ID <- sort(Reduce(intersect, list(colnames(KIRP_Met),colnames(TCGA_Exp),KIRP_c$ID))); length(COMMON_KIRP_ID) # 267
COMMON_LAML_ID <- sort(Reduce(intersect, list(colnames(LAML_Met),colnames(TCGA_Exp),LAML_c$ID))); length(COMMON_LAML_ID) #  91
COMMON_LGG__ID <- sort(Reduce(intersect, list(colnames(LGG__Met),colnames(TCGA_Exp),LGG__c$ID))); length(COMMON_LGG__ID) # 497
COMMON_LIHC_ID <- sort(Reduce(intersect, list(colnames(LIHC_Met),colnames(TCGA_Exp),LIHC_c$ID))); length(COMMON_LIHC_ID) # 365
COMMON_LUAD_ID <- sort(Reduce(intersect, list(colnames(LUAD_Met),colnames(TCGA_Exp),LUAD_c$ID))); length(COMMON_LUAD_ID) # 420
COMMON_LUSC_ID <- sort(Reduce(intersect, list(colnames(LUSC_Met),colnames(TCGA_Exp),LUSC_c$ID))); length(COMMON_LUSC_ID) # 353
COMMON_MESO_ID <- sort(Reduce(intersect, list(colnames(MESO_Met),colnames(TCGA_Exp),MESO_c$ID))); length(COMMON_MESO_ID) #  80
COMMON_OV___ID <- sort(Reduce(intersect, list(colnames(OV___Met),colnames(TCGA_Exp),OV___c$ID))); length(COMMON_OV___ID) #   7
COMMON_PAAD_ID <- sort(Reduce(intersect, list(colnames(PAAD_Met),colnames(TCGA_Exp),PAAD_c$ID))); length(COMMON_PAAD_ID) # 177
COMMON_PCPG_ID <- sort(Reduce(intersect, list(colnames(PCPG_Met),colnames(TCGA_Exp),PCPG_c$ID))); length(COMMON_PCPG_ID) # 175
COMMON_PRAD_ID <- sort(Reduce(intersect, list(colnames(PRAD_Met),colnames(TCGA_Exp),PRAD_c$ID))); length(COMMON_PRAD_ID) # 470
COMMON_READ_ID <- sort(Reduce(intersect, list(colnames(READ_Met),colnames(TCGA_Exp),READ_c$ID))); length(COMMON_READ_ID) #  94
COMMON_SKCM_ID <- sort(Reduce(intersect, list(colnames(SKCM_Met),colnames(TCGA_Exp),SKCM_c$ID))); length(COMMON_SKCM_ID) # 103
COMMON_STAD_ID <- sort(Reduce(intersect, list(colnames(STAD_Met),colnames(TCGA_Exp),STAD_c$ID))); length(COMMON_STAD_ID) # 327
COMMON_TGCT_ID <- sort(Reduce(intersect, list(colnames(TGCT_Met),colnames(TCGA_Exp),TGCT_c$ID))); length(COMMON_TGCT_ID) # 133
COMMON_THCA_ID <- sort(Reduce(intersect, list(colnames(THCA_Met),colnames(TCGA_Exp),THCA_c$ID))); length(COMMON_THCA_ID) # 496
COMMON_THYM_ID <- sort(Reduce(intersect, list(colnames(THYM_Met),colnames(TCGA_Exp),THYM_c$ID))); length(COMMON_THYM_ID) # 118
COMMON_UCEC_ID <- sort(Reduce(intersect, list(colnames(UCEC_Met),colnames(TCGA_Exp),UCEC_c$ID))); length(COMMON_UCEC_ID) # 418
COMMON_UCS__ID <- sort(Reduce(intersect, list(colnames(UCS__Met),colnames(TCGA_Exp),UCS__c$ID))); length(COMMON_UCS__ID) #  55
COMMON_UVM__ID <- sort(Reduce(intersect, list(colnames(UVM__Met),colnames(TCGA_Exp),UVM__c$ID))); length(COMMON_UVM__ID) #  77

ACC__c <- dplyr::filter(ACC__c, ID %in% COMMON_ACC__ID); ACC__c <- ACC__c[order(ACC__c$ID),]; ACC__Exp <- dplyr::select(TCGA_Exp, COMMON_ACC__ID); table(colnames(ACC__Exp)==ACC__c$ID); ACC__Met <- dplyr::select(ACC__Met, COMMON_ACC__ID)
BLCA_c <- dplyr::filter(BLCA_c, ID %in% COMMON_BLCA_ID); BLCA_c <- BLCA_c[order(BLCA_c$ID),]; BLCA_Exp <- dplyr::select(TCGA_Exp, COMMON_BLCA_ID); table(colnames(BLCA_Exp)==BLCA_c$ID); BLCA_Met <- dplyr::select(BLCA_Met, COMMON_BLCA_ID)
BRCA_c <- dplyr::filter(BRCA_c, ID %in% COMMON_BRCA_ID); BRCA_c <- BRCA_c[order(BRCA_c$ID),]; BRCA_Exp <- dplyr::select(TCGA_Exp, COMMON_BRCA_ID); table(colnames(BRCA_Exp)==BRCA_c$ID); BRCA_Met <- dplyr::select(BRCA_Met, COMMON_BRCA_ID)
CESC_c <- dplyr::filter(CESC_c, ID %in% COMMON_CESC_ID); CESC_c <- CESC_c[order(CESC_c$ID),]; CESC_Exp <- dplyr::select(TCGA_Exp, COMMON_CESC_ID); table(colnames(CESC_Exp)==CESC_c$ID); CESC_Met <- dplyr::select(CESC_Met, COMMON_CESC_ID)
CHOL_c <- dplyr::filter(CHOL_c, ID %in% COMMON_CHOL_ID); CHOL_c <- CHOL_c[order(CHOL_c$ID),]; CHOL_Exp <- dplyr::select(TCGA_Exp, COMMON_CHOL_ID); table(colnames(CHOL_Exp)==CHOL_c$ID); CHOL_Met <- dplyr::select(CHOL_Met, COMMON_CHOL_ID)
COAD_c <- dplyr::filter(COAD_c, ID %in% COMMON_COAD_ID); COAD_c <- COAD_c[order(COAD_c$ID),]; COAD_Exp <- dplyr::select(TCGA_Exp, COMMON_COAD_ID); table(colnames(COAD_Exp)==COAD_c$ID); COAD_Met <- dplyr::select(COAD_Met, COMMON_COAD_ID)
DLBC_c <- dplyr::filter(DLBC_c, ID %in% COMMON_DLBC_ID); DLBC_c <- DLBC_c[order(DLBC_c$ID),]; DLBC_Exp <- dplyr::select(TCGA_Exp, COMMON_DLBC_ID); table(colnames(DLBC_Exp)==DLBC_c$ID); DLBC_Met <- dplyr::select(DLBC_Met, COMMON_DLBC_ID)
ESCA_c <- dplyr::filter(ESCA_c, ID %in% COMMON_ESCA_ID); ESCA_c <- ESCA_c[order(ESCA_c$ID),]; ESCA_Exp <- dplyr::select(TCGA_Exp, COMMON_ESCA_ID); table(colnames(ESCA_Exp)==ESCA_c$ID); ESCA_Met <- dplyr::select(ESCA_Met, COMMON_ESCA_ID)
GBM__c <- dplyr::filter(GBM__c, ID %in% COMMON_GBM__ID); GBM__c <- GBM__c[order(GBM__c$ID),]; GBM__Exp <- dplyr::select(TCGA_Exp, COMMON_GBM__ID); table(colnames(GBM__Exp)==GBM__c$ID); GBM__Met <- dplyr::select(GBM__Met, COMMON_GBM__ID)
HNSC_c <- dplyr::filter(HNSC_c, ID %in% COMMON_HNSC_ID); HNSC_c <- HNSC_c[order(HNSC_c$ID),]; HNSC_Exp <- dplyr::select(TCGA_Exp, COMMON_HNSC_ID); table(colnames(HNSC_Exp)==HNSC_c$ID); HNSC_Met <- dplyr::select(HNSC_Met, COMMON_HNSC_ID)
KICH_c <- dplyr::filter(KICH_c, ID %in% COMMON_KICH_ID); KICH_c <- KICH_c[order(KICH_c$ID),]; KICH_Exp <- dplyr::select(TCGA_Exp, COMMON_KICH_ID); table(colnames(KICH_Exp)==KICH_c$ID); KICH_Met <- dplyr::select(KICH_Met, COMMON_KICH_ID)
KIRC_c <- dplyr::filter(KIRC_c, ID %in% COMMON_KIRC_ID); KIRC_c <- KIRC_c[order(KIRC_c$ID),]; KIRC_Exp <- dplyr::select(TCGA_Exp, COMMON_KIRC_ID); table(colnames(KIRC_Exp)==KIRC_c$ID); KIRC_Met <- dplyr::select(KIRC_Met, COMMON_KIRC_ID)
KIRP_c <- dplyr::filter(KIRP_c, ID %in% COMMON_KIRP_ID); KIRP_c <- KIRP_c[order(KIRP_c$ID),]; KIRP_Exp <- dplyr::select(TCGA_Exp, COMMON_KIRP_ID); table(colnames(KIRP_Exp)==KIRP_c$ID); KIRP_Met <- dplyr::select(KIRP_Met, COMMON_KIRP_ID)
LAML_c <- dplyr::filter(LAML_c, ID %in% COMMON_LAML_ID); LAML_c <- LAML_c[order(LAML_c$ID),]; LAML_Exp <- dplyr::select(TCGA_Exp, COMMON_LAML_ID); table(colnames(LAML_Exp)==LAML_c$ID); LAML_Met <- dplyr::select(LAML_Met, COMMON_LAML_ID)
LGG__c <- dplyr::filter(LGG__c, ID %in% COMMON_LGG__ID); LGG__c <- LGG__c[order(LGG__c$ID),]; LGG__Exp <- dplyr::select(TCGA_Exp, COMMON_LGG__ID); table(colnames(LGG__Exp)==LGG__c$ID); LGG__Met <- dplyr::select(LGG__Met, COMMON_LGG__ID)
LIHC_c <- dplyr::filter(LIHC_c, ID %in% COMMON_LIHC_ID); LIHC_c <- LIHC_c[order(LIHC_c$ID),]; LIHC_Exp <- dplyr::select(TCGA_Exp, COMMON_LIHC_ID); table(colnames(LIHC_Exp)==LIHC_c$ID); LIHC_Met <- dplyr::select(LIHC_Met, COMMON_LIHC_ID)
LUAD_c <- dplyr::filter(LUAD_c, ID %in% COMMON_LUAD_ID); LUAD_c <- LUAD_c[order(LUAD_c$ID),]; LUAD_Exp <- dplyr::select(TCGA_Exp, COMMON_LUAD_ID); table(colnames(LUAD_Exp)==LUAD_c$ID); LUAD_Met <- dplyr::select(LUAD_Met, COMMON_LUAD_ID)
LUSC_c <- dplyr::filter(LUSC_c, ID %in% COMMON_LUSC_ID); LUSC_c <- LUSC_c[order(LUSC_c$ID),]; LUSC_Exp <- dplyr::select(TCGA_Exp, COMMON_LUSC_ID); table(colnames(LUSC_Exp)==LUSC_c$ID); LUSC_Met <- dplyr::select(LUSC_Met, COMMON_LUSC_ID)
MESO_c <- dplyr::filter(MESO_c, ID %in% COMMON_MESO_ID); MESO_c <- MESO_c[order(MESO_c$ID),]; MESO_Exp <- dplyr::select(TCGA_Exp, COMMON_MESO_ID); table(colnames(MESO_Exp)==MESO_c$ID); MESO_Met <- dplyr::select(MESO_Met, COMMON_MESO_ID)
OV___c <- dplyr::filter(OV___c, ID %in% COMMON_OV___ID); OV___c <- OV___c[order(OV___c$ID),]; OV___Exp <- dplyr::select(TCGA_Exp, COMMON_OV___ID); table(colnames(OV___Exp)==OV___c$ID); OV___Met <- dplyr::select(OV___Met, COMMON_OV___ID)
PAAD_c <- dplyr::filter(PAAD_c, ID %in% COMMON_PAAD_ID); PAAD_c <- PAAD_c[order(PAAD_c$ID),]; PAAD_Exp <- dplyr::select(TCGA_Exp, COMMON_PAAD_ID); table(colnames(PAAD_Exp)==PAAD_c$ID); PAAD_Met <- dplyr::select(PAAD_Met, COMMON_PAAD_ID)
PCPG_c <- dplyr::filter(PCPG_c, ID %in% COMMON_PCPG_ID); PCPG_c <- PCPG_c[order(PCPG_c$ID),]; PCPG_Exp <- dplyr::select(TCGA_Exp, COMMON_PCPG_ID); table(colnames(PCPG_Exp)==PCPG_c$ID); PCPG_Met <- dplyr::select(PCPG_Met, COMMON_PCPG_ID)
PRAD_c <- dplyr::filter(PRAD_c, ID %in% COMMON_PRAD_ID); PRAD_c <- PRAD_c[order(PRAD_c$ID),]; PRAD_Exp <- dplyr::select(TCGA_Exp, COMMON_PRAD_ID); table(colnames(PRAD_Exp)==PRAD_c$ID); PRAD_Met <- dplyr::select(PRAD_Met, COMMON_PRAD_ID)
READ_c <- dplyr::filter(READ_c, ID %in% COMMON_READ_ID); READ_c <- READ_c[order(READ_c$ID),]; READ_Exp <- dplyr::select(TCGA_Exp, COMMON_READ_ID); table(colnames(READ_Exp)==READ_c$ID); READ_Met <- dplyr::select(READ_Met, COMMON_READ_ID)
SKCM_c <- dplyr::filter(SKCM_c, ID %in% COMMON_SKCM_ID); SKCM_c <- SKCM_c[order(SKCM_c$ID),]; SKCM_Exp <- dplyr::select(TCGA_Exp, COMMON_SKCM_ID); table(colnames(SKCM_Exp)==SKCM_c$ID); SKCM_Met <- dplyr::select(SKCM_Met, COMMON_SKCM_ID)
STAD_c <- dplyr::filter(STAD_c, ID %in% COMMON_STAD_ID); STAD_c <- STAD_c[order(STAD_c$ID),]; STAD_Exp <- dplyr::select(TCGA_Exp, COMMON_STAD_ID); table(colnames(STAD_Exp)==STAD_c$ID); STAD_Met <- dplyr::select(STAD_Met, COMMON_STAD_ID)
TGCT_c <- dplyr::filter(TGCT_c, ID %in% COMMON_TGCT_ID); TGCT_c <- TGCT_c[order(TGCT_c$ID),]; TGCT_Exp <- dplyr::select(TCGA_Exp, COMMON_TGCT_ID); table(colnames(TGCT_Exp)==TGCT_c$ID); TGCT_Met <- dplyr::select(TGCT_Met, COMMON_TGCT_ID)
THCA_c <- dplyr::filter(THCA_c, ID %in% COMMON_THCA_ID); THCA_c <- THCA_c[order(THCA_c$ID),]; THCA_Exp <- dplyr::select(TCGA_Exp, COMMON_THCA_ID); table(colnames(THCA_Exp)==THCA_c$ID); THCA_Met <- dplyr::select(THCA_Met, COMMON_THCA_ID)
THYM_c <- dplyr::filter(THYM_c, ID %in% COMMON_THYM_ID); THYM_c <- THYM_c[order(THYM_c$ID),]; THYM_Exp <- dplyr::select(TCGA_Exp, COMMON_THYM_ID); table(colnames(THYM_Exp)==THYM_c$ID); THYM_Met <- dplyr::select(THYM_Met, COMMON_THYM_ID)
UCEC_c <- dplyr::filter(UCEC_c, ID %in% COMMON_UCEC_ID); UCEC_c <- UCEC_c[order(UCEC_c$ID),]; UCEC_Exp <- dplyr::select(TCGA_Exp, COMMON_UCEC_ID); table(colnames(UCEC_Exp)==UCEC_c$ID); UCEC_Met <- dplyr::select(UCEC_Met, COMMON_UCEC_ID)
UCS__c <- dplyr::filter(UCS__c, ID %in% COMMON_UCS__ID); UCS__c <- UCS__c[order(UCS__c$ID),]; UCS__Exp <- dplyr::select(TCGA_Exp, COMMON_UCS__ID); table(colnames(UCS__Exp)==UCS__c$ID); UCS__Met <- dplyr::select(UCS__Met, COMMON_UCS__ID)
UVM__c <- dplyr::filter(UVM__c, ID %in% COMMON_UVM__ID); UVM__c <- UVM__c[order(UVM__c$ID),]; UVM__Exp <- dplyr::select(TCGA_Exp, COMMON_UVM__ID); table(colnames(UVM__Exp)==UVM__c$ID); UVM__Met <- dplyr::select(UVM__Met, COMMON_UVM__ID)